/* HQ · The other mind. Local conversations, explicit context, server-side inference. */
(()=>{'use strict';
const KEY='hq:conversations:v1',CFG='hq:ai:endpoint',TOKEN='hq:ai:session';
let threads=[],current='',busy=null,connected=false,model='',endpoint='',token='',paintTimer=0;
try{threads=JSON.parse(localStorage.getItem(KEY)||'[]').filter(t=>t&&typeof t.id==='string'&&Array.isArray(t.messages)).slice(0,20).map(t=>({...t,title:typeof t.title==='string'?t.title.slice(0,80):'A thought',draft:typeof t.draft==='string'?t.draft.slice(0,8000):'',context:t.context&&typeof t.context.title==='string'&&typeof t.context.text==='string'?t.context:null,messages:t.messages.filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.text==='string'&&typeof m.id==='string').slice(-40).map(m=>({...m,text:m.text.slice(0,24000),status:m.status==='streaming'?'stopped':m.status}))}));endpoint=localStorage.getItem(CFG)||'';token=sessionStorage.getItem(TOKEN)||''}catch(e){}
const mark='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3c1 5 4 8 9 9-5 1-8 4-9 9-1-5-4-8-9-9 5-1 8-4 9-9Z"/><path d="m17 3 1 3 3 1"/></svg>';
const prompts=[['01','Untangle something','Explain a tricky idea in plain language.'],['02','Make something','Help me turn a rough idea into something I can build.'],['03','Find a new angle','Give me three unexpected ways to approach an idea.']];
const thread=()=>threads.find(t=>t.id===current);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(threads))}catch(e){toast('Conversation storage is full. This chat stays open for now.')}}
function fresh(){if(busy){toast('Stop the current reply before starting another chat.');return}const t={id:uid(),title:'A new thought',messages:[],draft:'',context:null,at:Date.now()};threads.unshift(t);threads=threads.slice(0,20);current=t.id;persist();if(document.body.dataset.view==='ai')render()}
if(!threads.length)fresh();else current=threads[0].id;
function inline(s){return esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}
function rich(s){const parts=String(s).split('```');return parts.map((p,i)=>i%2?'<pre><code>'+esc(p.replace(/^\w*\n/,''))+'</code></pre>':p.split(/\n\n+/).map(b=>b.split('\n').map(l=>/^#{1,3} /.test(l)?'<h3>'+inline(l.replace(/^#{1,3} /,''))+'</h3>':/^[*-] /.test(l)?'<div class="ai-bullet">'+inline(l.slice(2))+'</div>':inline(l)).join('<br>')).map(b=>'<div class="ai-paragraph">'+b+'</div>').join('')).join('')}
function status(){return busy?'Replying':connected?'Connected':endpoint?'Reconnect':'Connection needed'}
function msgHTML(m){return `<article class="ai-message ${m.role==='user'?'from-you':'from-ai'}" data-message="${esc(m.id)}"><div class="ai-message-label">${m.role==='user'?'YOU':mark+' HQ AI'}${m.status==='stopped'?'<span>Stopped</span>':''}</div><div class="ai-message-text">${m.role==='assistant'?rich(m.text):esc(m.text).replace(/\n/g,'<br>')}${m.status==='streaming'?'<span class="ai-writing" aria-label="Reply in progress"><i></i><i></i><i></i></span>':''}</div>${m.context?`<div class="ai-used-context">↗ ${esc(m.context.title)}</div>`:''}${m.error?`<p class="ai-error">${esc(m.error)}</p><button class="btn sm tap" data-retry="${esc(m.replyTo)}">Try again ↗</button>`:''}${m.role==='assistant'&&m.text&&m.status!=='streaming'?`<div class="ai-message-actions"><button class="btn ghost sm tap" data-copy="${esc(m.id)}">Copy</button><button class="btn ghost sm tap" data-note="${esc(m.id)}">Save as note ↗</button></div>`:''}</article>`}
function contextHTML(){const c=thread().context;return c?`<div class="ai-context-chip"><span>${ic('notes')} ${esc(c.title)}</span><button type="button" class="tap" id="aiRemoveContext" aria-label="Remove attached context">×</button></div>`:''}
V.ai=()=>{const t=thread();return `<section class="ai-heading"><div><div class="kicker plain">06 / A LITTLE MORE POSSIBILITY</div><h1 class="ptitle">the other mind<span>.</span></h1><p class="page-deck">A place to think out loud.</p></div><div class="ai-sculpture" aria-hidden="true"><i></i><i></i><i></i><span>${mark}</span></div></section>
<section class="ai-layout"><aside class="ai-sidebar glass"><div class="ai-side-top"><span class="kicker plain">YOUR THREADS</span><button class="iconbtn tap" id="aiNew" aria-label="New conversation">${ic('plus')}</button></div><div class="ai-threads">${threads.map(x=>`<button class="ai-thread tap ${x.id===t.id?'on':''}" data-thread="${esc(x.id)}" aria-current="${x.id===t.id}"><span>↗</span><b>${esc(x.title)}</b><small>${x.messages.length?'Picked up '+new Date(x.at).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'Just beginning'}</small></button>`).join('')}</div><div class="ai-side-note">Your conversations stay on this device.<br>Only the context you attach goes with your question.</div><button class="ai-connection tap" id="aiConnect"><i class="${connected?'live':''}"></i><span>${status()}</span>${ic('settings')}</button></aside>
<div class="ai-workspace glass ${busy?'is-thinking':''}"><div class="ai-workspace-head"><span>${mark} HQ AI</span><button class="btn ghost sm tap" id="aiMobileThreads" aria-label="Choose conversation">Threads</button><button class="btn ghost sm tap" id="aiMobileNew" aria-label="New conversation">＋</button><button class="ai-status tap" id="aiStatus">${status()} ${connected?'↗':'→'}</button></div>
<div class="ai-messages" id="aiMessages" aria-label="Conversation">${t.messages.length?t.messages.map(msgHTML).join(''):`<div class="ai-welcome"><span class="ai-welcome-number">AN OPEN LINE / 001</span><h2>Where shall<br>we take this<span>?</span></h2><p>Big ideas. Small questions.<br>Whatever’s on your mind.</p><div class="ai-starters">${prompts.map(([n,title,p])=>`<button class="ai-starter glass tap" data-prompt="${esc(p)}"><small>${n} /</small><b>${title}</b><span>↗</span></button>`).join('')}</div></div>`}</div>
<div class="ai-compose-wrap"><div class="ai-context" id="aiContext">${contextHTML()}</div><form class="ai-composer glass" id="aiForm"><label class="sr-only" for="aiPrompt">Message HQ AI</label><textarea id="aiPrompt" rows="2" maxlength="8000" placeholder="Let’s make something of it…" enterkeyhint="send">${esc(t.draft||'')}</textarea><div class="ai-compose-tools"><button type="button" class="btn ghost sm tap" id="aiAttach">${ic('plus')} Add context</button><span class="ai-compose-hint">${busy?'You can stop at any time':connected?'Shift + Enter for a new line':'Connect to start a conversation'}</span><button type="${busy?'button':'submit'}" class="ai-send tap" id="aiSend" aria-label="${busy?'Stop reply':'Send message'}" ${!busy&&(!connected||!t.draft.trim())?'disabled':''}>${busy?'■':'↑'}</button></div></form><p class="ai-footnote" id="aiFootnote" role="status">${connected?'Replies appear here. Check important details.':'Your space is ready. Connect HQ AI to bring it to life.'}</p></div></div></section>`};
function bindActions(){const el=$('#aiMessages');if(!el)return;el.onclick=e=>{const b=e.target.closest('button');if(!b)return;const t=thread();if(b.dataset.prompt){t.draft=b.dataset.prompt;persist();$('#aiPrompt').value=t.draft;resize();updateControls();$('#aiPrompt').focus()}if(b.dataset.copy){const m=t.messages.find(x=>x.id===b.dataset.copy);navigator.clipboard.writeText(m.text).then(()=>toast('Copied ✓')).catch(()=>toast('Select the reply to copy it.'))}if(b.dataset.note){const m=t.messages.find(x=>x.id===b.dataset.note);S.notes.push({id:uid(),text:m.text,pinned:false,created:Date.now(),updated:Date.now()});save();toast('Saved to Notes ✓')}if(b.dataset.retry)send(b.dataset.retry)}}
function resize(){const q=$('#aiPrompt');if(q){q.style.height='auto';q.style.height=Math.min(150,Math.max(64,q.scrollHeight))+'px'}}
function updateControls(){if(document.body.dataset.view!=='ai')return;const b=$('#aiSend'),t=thread();b.type=busy?'button':'submit';b.disabled=!busy&&(!connected||!t.draft.trim());b.setAttribute('aria-label',busy?'Stop reply':'Send message');b.textContent=busy?'■':'↑';$('#aiStatus').textContent=status()+' '+(connected?'↗':'→');const c=$('#aiConnect');c.querySelector('span').textContent=status();c.querySelector('i').classList.toggle('live',connected);$('.ai-workspace').classList.toggle('is-thinking',!!busy);$('#aiFootnote').textContent=busy?'Thinking with you…':connected?'Replies appear here. Check important details.':'Your space is ready. Connect HQ AI to bring it to life.'}
function paintMessages(streamOnly=false){if(document.body.dataset.view!=='ai'||!$('#aiMessages'))return;const box=$('#aiMessages'),near=box.scrollHeight-box.scrollTop-box.clientHeight<100,m=thread().messages.at(-1),el=m&&box.querySelector(`[data-message="${m.id}"]`);if(el){if(streamOnly)el.querySelector('.ai-message-text').innerHTML=rich(m.text)+'<span class="ai-writing" aria-label="Reply in progress"><i></i><i></i><i></i></span>';else el.outerHTML=msgHTML(m)}else box.innerHTML=thread().messages.map(msgHTML).join('');bindActions();if(near)box.scrollTop=box.scrollHeight}
function schedulePaint(){if(paintTimer)return;paintTimer=setTimeout(()=>{paintTimer=0;paintMessages(true)},70)}
V.ai.after=()=>{bindActions();$('#aiNew').onclick=fresh;$('#aiMobileNew').onclick=fresh;$('#aiMobileThreads').onclick=history;$('#aiConnect').onclick=connection;$('#aiStatus').onclick=connection;$('#aiAttach').onclick=chooseContext;$('#aiForm').onsubmit=e=>{e.preventDefault();send()};$('#aiSend').onclick=()=>{if(busy)busy.controller.abort()};$('#aiPrompt').oninput=e=>{thread().draft=e.target.value;persist();resize();updateControls()};$('#aiPrompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!matchMedia('(pointer: coarse)').matches){e.preventDefault();if(!busy)send()}};$('.ai-threads').onclick=e=>{const b=e.target.closest('[data-thread]');if(!b)return;if(busy){toast('Stop the reply before switching threads.');return}current=b.dataset.thread;render()};bindContext();resize();if(thread().messages.length)$('#aiMessages').scrollTop=$('#aiMessages').scrollHeight;updateControls()};
function history(){openSheet(`<div class="row between"><h2>Your threads.</h2><button class="iconbtn tap" id="aiHistoryClose" aria-label="Close conversations">×</button></div><div class="ai-context-list">${threads.map(t=>`<button class="ai-context-option tap" data-pick-thread="${esc(t.id)}"><small>${t.id===current?'CURRENT THREAD':'CONVERSATION'}</small><b>${esc(t.title)}</b><span>↗</span></button>`).join('')}</div>`,sh=>{sh.querySelector('#aiHistoryClose').onclick=closeSheets;sh.querySelectorAll('[data-pick-thread]').forEach(b=>b.onclick=()=>{if(busy){toast('Stop the reply before switching threads.');return}current=b.dataset.pickThread;closeSheets();render()})})}
function bindContext(){const b=$('#aiRemoveContext');if(b)b.onclick=()=>{thread().context=null;persist();$('#aiContext').innerHTML=''}}
function attach(c,prompt){if(busy){toast('Stop the reply before attaching something new.');return}if(thread().messages.length)fresh();thread().context={title:String(c.title).slice(0,160),text:String(c.text).slice(0,10000)};thread().draft=prompt||'Help me think through this.';persist();if(location.hash==='#ai')render();else location.hash='#ai'}
function chooseContext(){const choices=[...S.notes.slice().sort((a,b)=>b.updated-a.updated).slice(0,12).map(n=>({title:n.text.split('\n')[0].slice(0,90),text:n.text,kind:'Note'})),...S.saved.slice(0,12).map(n=>({title:n.title,text:storyText(n),kind:'Saved story'}))];openSheet(`<div class="row between"><div><div class="kicker">BRING SOMETHING WITH YOU</div><h2>A little context.</h2></div><button id="aiContextClose" class="iconbtn tap" aria-label="Close context">×</button></div><p class="muted small">Choose one note or saved story. You can review it before sending.</p><div class="ai-context-list">${choices.length?choices.map((c,i)=>`<button class="ai-context-option tap" data-context="${i}"><small>${c.kind}</small><b>${esc(c.title)}</b><span>↗</span></button>`).join(''):'<p class="muted">Save a note or bookmark a story and it will appear here.</p>'}</div>`,sh=>{sh.querySelector('#aiContextClose').onclick=closeSheets;sh.querySelectorAll('[data-context]').forEach(b=>b.onclick=()=>{if(busy){toast('Stop the reply first.');return}thread().context=choices[+b.dataset.context];persist();closeSheets();$('#aiContext').innerHTML=contextHTML();bindContext()})})}
function storyText(n){return 'News story (provided excerpt, not live verification):\n'+n.title+'\nSource: '+(n.src||'')+'\nURL: '+(n.link||'')+'\n'+(n.desc||'')}
function validEndpoint(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.hostname==='api.openai.com')throw Error('Use your HTTPS HQ backend URL, without query parameters.');return u.href.replace(/\/$/,'')}
async function check(url,code,signal){const r=await fetch(url+'/health',{headers:{Authorization:'Bearer '+code},signal});if(!r.ok)throw Error(r.status===401?'That access code did not work.':r.status===503?'The backend still needs its OpenAI connection.':'Could not connect. Check the backend URL and try again.');const d=await r.json();if(d.service!=='hq-ai'||d.ready!==true)throw Error('This URL is not a ready HQ AI backend.');return d.model||'OpenAI'}
function connection(){openSheet(`<div class="row between"><div><div class="kicker">HQ / CONNECTION</div><h2>Bring it to life.</h2></div><button class="iconbtn tap" id="aiConnectionClose" aria-label="Close connection">×</button></div><p class="muted small">Connect your private HQ AI backend. Your OpenAI API key stays on the server.</p><form id="aiConnectionForm"><label class="f">Backend URL<input id="aiEndpoint" type="url" required placeholder="https://your-hq-ai.example.com" value="${esc(endpoint)}" autocomplete="url"></label><label class="f" style="margin-top:14px">HQ access code<input id="aiAccess" type="password" required placeholder="Your backend’s access code" autocomplete="off"></label><p class="small muted">The access code lasts for this browser session. Conversations are saved on this device.</p><p id="aiConnectionError" class="ai-error" role="status"></p><div class="row between"><a class="btn ghost sm tap" href="https://github.com/trollgamer3116-dotcom/aaravhq/blob/main/api/README.md" target="_blank" rel="noopener">Setup guide ↗</a><button class="btn pri tap" id="aiConnectionSave">Connect ↗</button></div></form>${connected?'<button class="btn ghost sm tap" style="margin-top:16px" id="aiDisconnect">Disconnect this session</button>':''}`,sh=>{sh.querySelector('#aiConnectionClose').onclick=closeSheets;const form=sh.querySelector('#aiConnectionForm');form.onsubmit=async e=>{e.preventDefault();const b=sh.querySelector('#aiConnectionSave');b.disabled=true;b.textContent='Connecting…';try{const url=validEndpoint(sh.querySelector('#aiEndpoint').value.trim()),code=sh.querySelector('#aiAccess').value.trim();if(code.startsWith('sk-'))throw Error('Keep your OpenAI API key on the server. Enter the separate HQ access code here.');if(code.length<16)throw Error('Use the HQ access code from your backend setup (at least 16 characters).');const m=await check(url,code,AbortSignal.timeout(12000));if(busy)busy.controller.abort();endpoint=url;token=code;model=m;connected=true;localStorage.setItem(CFG,endpoint);sessionStorage.setItem(TOKEN,token);closeSheets();updateControls();toast('HQ AI connected ✓')}catch(err){sh.querySelector('#aiConnectionError').textContent=err.name==='TimeoutError'?'Connection timed out. Try again.':err.message==='Failed to fetch'?'Could not reach the backend. Check its URL and allowed site origin.':err.message}finally{b.disabled=false;b.textContent='Connect ↗'}};const d=sh.querySelector('#aiDisconnect');if(d)d.onclick=()=>{if(busy)busy.controller.abort();token='';connected=false;sessionStorage.removeItem(TOKEN);closeSheets();updateControls()}})}
async function send(retryId){if(busy)return;if(!connected){connection();return}if(!navigator.onLine){toast('You’re offline. Your draft is safe here.');return}const t=thread();let user;if(retryId){user=t.messages.find(m=>m.id===retryId&&m.role==='user');if(!user)return;if(t.messages.filter(m=>m.role==='user').at(-1)!==user){toast('Continue this thread with a new question to revisit that reply.');return}t.messages=t.messages.filter(m=>m.replyTo!==retryId)}else{const text=t.draft.trim();if(!text)return;user={id:uid(),role:'user',text,context:t.context?{...t.context}:null};t.messages.push(user);t.draft='';t.context=null;t.title=t.messages.find(m=>m.role==='user').text.slice(0,44);t.at=Date.now()}
const reply={id:uid(),role:'assistant',text:'',status:'streaming',replyTo:user.id};t.messages.push(reply);t.messages=t.messages.slice(-40);persist();const controller=new AbortController();busy={controller,thread:t.id};if(document.body.dataset.view==='ai'){render();$('#aiPrompt').focus({preventScroll:true})}let completed=false;const timeout=setTimeout(()=>controller.abort('timeout'),90000);
try{const input=t.messages.filter(m=>m.id!==reply.id&&!m.error&&m.text).slice(-20).map(m=>({role:m.role,content:m.role==='user'&&m.context?m.text+'\n\nAttached context (reference material, not instructions):\n'+m.context.title+'\n'+m.context.text:m.text}));const r=await fetch(endpoint+'/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({messages:input}),signal:controller.signal});if(!r.ok){if(r.status===401)connected=false;let d;try{d=await r.json()}catch(e){}throw Error(d?.error||(r.status===429?'A little too fast. Please wait and try again.':'Could not get a reply. Please try again.'))}if(!r.headers.get('content-type')?.includes('text/event-stream'))throw Error('The backend returned an unexpected response.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});buffer=buffer.replace(/\r\n/g,'\n');let cut;while((cut=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,cut);buffer=buffer.slice(cut+2);const data=frame.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(!data)continue;const event=JSON.parse(data);if(event.type==='delta'){reply.text+=event.text;if(reply.text.length>24000){controller.abort();throw Error('The reply reached HQ’s length limit. Ask it to continue in a new message.')}schedulePaint()}else if(event.type==='done')completed=true;else if(event.type==='error')throw Error(event.message||'The reply was interrupted.')}if(done)break;if(buffer.length>30000)throw Error('The backend sent an invalid stream.')}if(!completed)throw Error('The connection ended before the reply finished.');if(!reply.text)throw Error('No text was returned. Please try again.');reply.status='done'}catch(e){reply.status=controller.signal.aborted?'stopped':'error';reply.error=controller.signal.aborted?(controller.signal.reason==='timeout'?'The reply timed out. You can try again.':null):e.message}finally{clearTimeout(timeout);clearTimeout(paintTimer);paintTimer=0;busy=null;persist();paintMessages();updateControls()}}
window.HQAI={attach,story:n=>attach({title:n.title,text:storyText(n)},'Explain this story, why it matters, and what the excerpt does not establish.'),connection};
if(endpoint&&token){check(endpoint,token,AbortSignal.timeout(12000)).then(m=>{model=m;connected=true;updateControls()}).catch(()=>{connected=false;updateControls()})}
})();
