window.CREW = {
 tony:{n:"Tony Stark",e:"🦾",c:"#ff6b6b"}, vegeta:{n:"Vegeta",e:"👑",c:"#7aa2ff"},
 gp:{n:"Grand Priest",e:"🕊️",c:"#9be7ff"}, vados:{n:"Vados",e:"🔮",c:"#c49bff"},
 marcarita:{n:"Marcarita",e:"😈",c:"#ff9bd2"}, kusu:{n:"Kusu",e:"🍼",c:"#ffd59b"},
 bulma:{n:"Bulma",e:"🧪",c:"#6be6c1"}, zeno:{n:"The Zenos",e:"👾",c:"#ffe36b"}
};
window.LINES = [
 ["tony","Aarav, I built a suit in a cave. You can do one problem set in a bedroom with WiFi."],
 ["vegeta","Rest day? No."],
 ["gp","Take your time, young Aarav. The universe will wait. I've made sure of it."],
 ["vados","What a lovely plan. Shame if you actually had to follow it."],
 ["marcarita","I hid your phone. You're welcome. Or not. Hehe."],
 ["kusu","Aarav, I think you are doing a very good job and I made you a little sticker."],
 ["bulma","I solved this in 4 minutes at age 9. Anyway, you've got this, nerd."],
 ["zeno",":D"],
 ["tony","Physics is just vibes with units. Get the units right, genius."],
 ["vegeta","A Saiyan doesn't 'check Instagram for five minutes.' Neither do you."],
 ["gp","Hohoho. Anyone who disturbs Aarav's study session will be erased. Gently."],
 ["vados","Your rank predictor is very optimistic. So is a toddler."],
 ["kusu","Studying is so fun when you do it! I believe in you so much it is silly."],
 ["bulma","Drink water. Your brain is 75% of it, and the rest is anime."],
 ["zeno","(to everyone else) Silence."],
 ["marcarita","If you don't do your todos I'm telling the Grand Priest. He'll just pat you though. Unfair."],
 ["tony","JARVIS, remind Aarav that F = ma, not F = 'meh'."]
];
window.LORE_CANON = [
 {t:"The Grand Priest Nepotism Arc",b:"The Tournament of Power rules were simple: no favorites. Then Aarav showed up 3 minutes late and the Grand Priest said, \"Hohoho, the clock is merely a suggestion.\" The clock was then erased. Vados filed a complaint. It was elegantly lost forever."},
 {t:"The Bulma Divorce to Four-Wife Reconciliation Saga",b:"It started with a tragic argument about who left the capsule car on read. It ended with Bulma throwing a reconciliation dinner so big that four separate wives showed up, all of them got along, and everyone cried over cake. Vegeta said \"No.\" Then hugged everyone. Wholesome canon. Don't ask questions."},
 {t:"Zeno Privilege Lore",b:"Grand rule of the multiverse: when the Zenos speak to Aarav, they say \":D\". When anyone else talks, they say \"Silence.\" Beerus once asked why. He has not spoken since. Tony is working on a suit to understand it. It's going badly."},
 {t:"Aarav's Power Escalation, Part I: Ultra Instinct",b:"Aarav dodged three JEE mocks, two relatives asking \"rank kitna aayega\", and one group project, all without thinking. Whis called it Ultra Instinct. Aarav called it \"just vibes.\""},
 {t:"Aarav's Power Escalation, Part II: Beyond Gods",b:"After solving a rotational mechanics problem on the first try, Aarav's aura turned silver, then gold, then RGB. Bulma tried to patent it. Vegeta whispered \"...Kakarot who?\""},
 {t:"Aarav's Power Escalation, Final Form: Omni King",b:"The Zenos looked at Aarav and said \":D\". Then they handed him a third throne. The Grand Priest smiled warmly. Everyone else was told \"Silence.\" Aarav is now Omni King of Study Breaks. His first decree: snacks."},
 {t:"THE BIDDING GAME",b:"Anyone owing more than 1,000 zeni to anybody is summoned to the Zeno Court for THE BIDDING GAME. Tony bid his arc reactor. Marcarita bid someone else's stuff. Vados bid \"one (1) polite silence.\" The Zenos only accepted Aarav's bid: \":D\". Debts dissolved. Economy reformed. Bulma is furious."}
];
window.LORE_GAGS = [
 ["vegeta","Kusu asked Vegeta if he wanted to play tag. Vegeta said \"No.\" Kusu said, \"That is okay, you are still my friend.\" Vegeta stayed in his room for six hours processing this."],
 ["tony","Tony tried to upgrade the Zenos' throne with a touchscreen. The Zenos said \"Silence.\" The touchscreen said \"Silence.\" Tony is in therapy."],
 ["vados","Vados to Tony: \"Your suit is very impressive. For a can.\""],
 ["marcarita","Marcarita swapped Vegeta's protein powder with powdered sugar. He's never had more energy. He's never been more confused."],
 ["bulma","Bulma made a Dragon Radar for lost socks. It works. It found 47 socks inside Vegeta's training room. Nobody knows why."],
 ["gp","Someone told Aarav his handwriting was messy. The Grand Priest smiled. That person now writes in perfect calligraphy and cannot stop."],
 ["kusu","Kusu announced, \"I have made a spreadsheet of everyone's birthdays and also their favorite juices.\" It was the most organized document in all 12 universes."],
 ["zeno","Whis asked the Zenos what's for lunch. \"Silence.\" Aarav asked. \":D\" (Lunch was pizza.)"],
 ["tony","Tony vs Bulma tech-off. Bulma won. Tony said it was rigged. The judge was the Grand Priest. It was absolutely rigged. In Aarav's favor. Aarav wasn't competing."],
 ["vegeta","Vegeta tried meditation. Lasted 4 seconds. Said \"No.\" to the concept of peace."],
 ["vados","Marcarita: \"Vados, am I your favorite sister?\" Vados: \"You're certainly one of them.\""],
 ["marcarita","Marcarita set every clock in HQ forward 10 minutes. Everyone was early for once. She's furious it helped."],
 ["bulma","Bulma roasted Tony's goatee so hard it grew back out of spite."],
 ["kusu","Kusu said, \"Aarav, I drew you as a big strong physics man with a cape.\" It is now framed in the Zeno Palace."],
 ["gp","The Grand Priest hosted a quiz night. Every answer was \"Aarav.\" Every answer was correct."],
 ["tony","Tony named his new AI 'NOT-JARVIS'. It immediately started asking Aarav if he'd finished his DPP."],
 ["vegeta","Someone asked Vegeta to rate Aarav's focus session. \"Acceptable.\" That is the highest compliment in Saiyan history."],
 ["zeno","A Zeno pressed the 'erase' button. Aarav said \"please don't.\" The Zeno pressed 'unerase'. Nobody knew that button existed."],
 ["marcarita","Marcarita told the group chat Aarav was getting 300/300. Now 400 people are DMing him for notes."],
 ["vados","Vados reviewed Tony's code: \"How wonderfully brave of you to ship this.\""],
 ["bulma","Bulma built a capsule that holds infinite snacks. Vegeta found the limit. It was 900 sandwiches."],
 ["kusu","Kusu said \"I would like to file a formal complaint that Monday is too long.\" Motion passed unanimously."],
 ["tony","Tony tried to explain quantum tunneling to Vegeta. Vegeta punched through the wall and said \"Like this?\" Technically no. Spiritually yes."],
 ["gp","A god of destruction yawned during Aarav's presentation. He is now a god of polite applause."],
 ["vegeta","Vegeta saw Aarav's 7-day streak and quietly started his own. He's on day 2. Don't mention it."],
 ["vados","Vados to a guy who said JEE is easy: \"Of course. Let's see your rank, darling.\""],
 ["zeno","The Zenos learned to clap. They only clap for Aarav's correct answers. The palace shakes every time."],
 ["marcarita","Marcarita hid the TV remote inside a Senzu bean jar. Yamcha ate it. Remote fully healed."],
 ["bulma","Bulma installed a lie detector in HQ. First test: Tony said \"I'm humble.\" Machine exploded."],
 ["kusu","Kusu politely asked Beerus to stop being grumpy, \"because it makes the room feel scratchy.\" He did."],
 ["tony","Tony and Aarav built a rocket. Tony did the design. Aarav did the calculations. Only one of them got it right. (It was Aarav.)"],
 ["gp","The Grand Priest gave Aarav a 'Free Pass' card. The fine print says 'Valid forever. All universes. Hohoho.'"],
 ["vegeta","Goku asked to borrow Aarav's notes. Vegeta, unprompted: \"No.\""],
 ["vados","Vados on the group project: \"Everyone contributed equally. Aarav did the work, and the rest of you contributed oxygen consumption.\""],
 ["marcarita","Marcarita put googly eyes on every capsule in Capsule Corp. Stock went up 12%."]
];
