/* HQ · a personal music shelf with an honest handoff to YouTube Music. */
(()=>{'use strict';
const legacyView=V.music,legacyAfter=V.music.after;
let embedded=false,filter='all',query='',limit=24,removed=null;
const MIX='https://music.youtube.com/';
function url(item){if(!item||!['video','playlist'].includes(item.type)||!/^[-\w]+$/.test(item.id))return MIX;return item.type==='video'?'https://music.youtube.com/watch?v='+encodeURIComponent(item.id):'https://music.youtube.com/playlist?list='+encodeURIComponent(item.id)}
function library(){ensureMusic();return S.music.lib.filter(x=>!x.def&&['video','playlist'].includes(x.type)&&/^[-\w]+$/.test(x.id))}
function name(x){return cleanT(x.title)||'Saved discovery'}
function artwork(x){return x.type==='video'?thumb(x.id,'hqdefault'):''}
function handoff(x){if(playing&&YTP)try{YTP.pauseVideo()}catch(_){}if(x){x.openedAt=Date.now();save()}/* The destination owns playback and shuffle. Never label an open as a play. */}
function card(x){const art=artwork(x),later=x.shelf==='later';return `<article class="glass music-save"><a class="music-cover tap" href="${url(x)}" target="_blank" rel="noopener" data-open-music="${esc(x.id)}" aria-label="Open ${esc(name(x))} in YouTube Music">${art?`<img src="${art}" alt="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin">`:'<span class="shelf-record" aria-hidden="true"><i></i></span>'}<span class="cover-arrow">↗</span></a><div class="music-save-copy"><span class="music-item-kind">${x.type==='video'?'SONG / VIDEO':'PLAYLIST'}${later?' · LATER':''}</span><h3>${esc(name(x))}</h3>${x.openedAt?'<p class="music-opened">Opened from HQ '+esc(ago(x.openedAt))+'</p>':''}<a class="music-open-link tap" href="${url(x)}" target="_blank" rel="noopener" data-open-music="${esc(x.id)}">YouTube Music ↗</a><div class="music-save-actions"><button class="iconbtn tap" data-fav="${esc(x.id)}" aria-label="Favourite ${esc(name(x))}" aria-pressed="${!!x.favourite}">${x.favourite?'♥':'♡'}</button><button class="btn ghost sm tap" data-later="${esc(x.id)}" aria-label="${later?'Move to discoveries':'Listen later'}: ${esc(name(x))}">${later?'✓ Saved':'＋ Later'}</button><button class="btn ghost sm tap" data-hq-play="${esc(x.id)}">Play in HQ</button><button class="iconbtn tap" data-remove-music="${esc(x.id)}" aria-label="Remove ${esc(name(x))}">×</button></div></div></article>`}
function shelfHTML(){const all=library(),items=all.filter(x=>(filter==='all'||filter==='later'&&x.shelf==='later'||filter==='discoveries'&&x.shelf!=='later'||filter==='favourites'&&x.favourite)&&name(x).toLowerCase().includes(query.toLowerCase()));
 return `${removed?'<div class="music-undo" role="status">Removed from your shelf.<button class="btn ghost sm tap" id="musicUndo">Undo</button></div>':''}${items.length?`<div class="music-shelf-grid">${items.slice(0,limit).map(card).join('')}</div>${items.length>limit?'<button class="btn sm tap" id="musicMore">Show more discoveries</button>':''}`:`<div class="music-empty"><span aria-hidden="true">${filter==='later'?'↗':'♪'}</span><h3>${query?'No matches.':filter==='favourites'?'Your favourites live here.':filter==='later'?'For your next listen.':'Keep the good stuff.'}</h3><p>${query?'Try another title or shelf.':filter==='favourites'?'Tap a heart on any saved discovery.':'Hear something good? Copy its YouTube Music link and save it here.'}</p>${!query&&filter!=='favourites'?'<button class="btn sm tap" data-add-music>Save a discovery</button>':''}</div>`}`}
function hubHTML(){const items=library(),later=items.filter(x=>x.shelf==='later').length;
 return `<section class="phead music-hub-head"><div class="kicker plain">04 / MUSIC · YOUR SOUNDTRACK</div><h1 class="ptitle">the rotation<i>.</i></h1><p class="music-deck">Find it there. Keep it here.</p></section>
 <section class="glass music-launch"><div class="music-launch-copy"><span class="kicker">YOU PICK THE MOMENT</span><h2>A good day<br>needs a <em>soundtrack.</em></h2><p>Your mixes and shuffle live in YouTube Music.<br>This is your place to keep the discoveries.</p><a class="btn music-yt tap" id="musicMix" href="${MIX}" target="_blank" rel="noopener">${IC.play} Open YouTube Music ↗</a><span class="music-launch-note">Choose your mix there. No account connection needed.</span></div><div class="music-orbit" aria-hidden="true"><div class="music-record"><i></i><b>HQ<br><small>SIDE / A</small></b></div><span class="record-caption">THE GOOD STUFF / ON REPEAT</span></div></section>
 <section class="music-shelf"><div class="music-shelf-heading"><div><span class="kicker">YOUR PERSONAL LINER NOTES</span><h2>The collection<span>.</span></h2><p id="musicCounts">${items.length} saved · ${later} for later</p></div><button class="btn sm tap" id="musicAdd">${ic('plus')} Save a discovery</button></div><div class="music-shelf-tools"><div class="music-shelf-tabs" aria-label="Music shelves">${[['all','All'],['discoveries','Discoveries'],['later','Listen later'],['favourites','Favourites']].map(([id,label])=>`<button class="tap" data-music-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div><label class="music-search">${ic('search')}<input type="search" id="musicSearch" aria-label="Search saved music" placeholder="Search your collection" maxlength="100" value="${esc(query)}"></label></div><div id="musicShelf">${shelfHTML()}</div></section>
 <section class="glass music-hq-option"><div><span class="kicker">A SECOND WAY TO LISTEN</span><h3>Stay a little longer.</h3><p>Use the YouTube player inside HQ when you want to stay here.</p></div><button class="btn sm tap" id="musicEmbedded">Open HQ player ${ic('chevR')}</button></section>`}
function paint(){const el=document.getElementById('musicShelf');if(!el)return;el.innerHTML=shelfHTML();const a=library();document.getElementById('musicCounts').textContent=`${a.length} saved · ${a.filter(x=>x.shelf==='later').length} for later`;document.querySelectorAll('[data-music-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.musicFilter===filter)));document.querySelectorAll('.music-cover img').forEach(img=>img.onerror=()=>{img.hidden=true});if(window.FX)FX.refresh()}
function addSheet(){openSheet(`<div class="row between"><div><div class="kicker">A GOOD FIND</div><h2>Save a discovery.</h2></div><button class="iconbtn tap" id="musicAddClose" aria-label="Close music form">×</button></div><form id="musicSaveForm" class="music-save-form"><label>YouTube / YouTube Music link<input type="text" id="musicLink" placeholder="Paste a song or playlist link" autocomplete="off" required maxlength="2048"></label><label>Title <span class="muted">(optional)</span><input type="text" id="musicName" placeholder="Give it a name" maxlength="120"></label><label>Save to<select id="musicDestination"><option value="discoveries">Discoveries</option><option value="later">Listen later</option></select></label><p id="musicFormError" role="alert" class="err" hidden></p><button class="btn pri tap" type="submit">Save to collection</button></form>`,sh=>{sh.querySelector('#musicDestination').value=filter==='later'?'later':'discoveries';sh.querySelector('#musicAddClose').onclick=closeSheets;const form=sh.querySelector('form');form.onsubmit=e=>{e.preventDefault();const parsed=parseYT(form.querySelector('#musicLink').value.trim()),error=form.querySelector('#musicFormError');if(!parsed){error.hidden=false;error.textContent='Paste a valid YouTube or YouTube Music song or playlist link.';return}
 const existing=library().find(x=>x.id===parsed.id&&x.type===parsed.type);if(existing){error.hidden=false;error.textContent='Already saved. Find it in your collection, or move it to Listen later.';return}
 const custom=form.querySelector('#musicName').value.trim().slice(0,120),item={id:parsed.id,type:parsed.type,title:custom||(parsed.type==='video'?'Saved song':'Saved playlist'),shelf:form.querySelector('#musicDestination').value,added:Date.now()};S.music.lib.push(item);save();closeSheets();paint();toast('Saved to '+(item.shelf==='later'?'Listen later.':'Discoveries.'));
 if(!custom&&item.type==='video')ytMeta(item.id).then(meta=>{if(meta?.t&&S.music.lib.includes(item)){item.title=meta.t;save();if(!embedded&&location.hash==='#music')paint()}});
 }} )}
function enterPlayer(){const available=library();if(!curVid&&available.length&&!available.some(x=>x.id===S.music.cur)){S.music.cur=available[0].id;save()}embedded=true;render()}
function bindHub(){const view=document.getElementById('view');document.getElementById('musicSearch').oninput=e=>{query=e.target.value;limit=24;paint()};
 view.onclick=e=>{if(document.body.dataset.view!=='music'||embedded)return;const target=e.target.closest('button,a');if(!target)return;
 if(target.matches('#musicMix')){handoff();return}
 if(target.matches('#musicAdd,[data-add-music]')){addSheet();return}
 if(target.matches('#musicEmbedded')){enterPlayer();return}
 if(target.dataset.musicFilter){filter=target.dataset.musicFilter;limit=24;paint();return}
 if(target.id==='musicMore'){limit+=24;paint();return}
 if(target.id==='musicUndo'&&removed){S.music.lib.splice(Math.min(removed.index,S.music.lib.length),0,removed.item);removed=null;save();paint();return}
 const id=target.dataset.openMusic||target.dataset.fav||target.dataset.later||target.dataset.hqPlay||target.dataset.removeMusic;
 const item=library().find(x=>x.id===id);if(!item)return;
 if(target.dataset.openMusic){handoff(item);return}
 if(target.dataset.hqPlay){embedded=true;render();playItem(item,true);return}
 if(target.dataset.fav){item.favourite=!item.favourite}
 if(target.dataset.later){item.shelf=item.shelf==='later'?'discoveries':'later'}
 if(target.dataset.removeMusic){const index=S.music.lib.indexOf(item);removed={item,index};S.music.lib.splice(index,1);if(S.music.cur===item.id)S.music.cur=S.music.lib[0]?.id||DEF_PL.id}
 save();paint();
 };
 document.querySelectorAll('.music-cover img').forEach(img=>img.onerror=()=>{img.hidden=true});
}
V.music=()=>embedded&&!library().length&&!curVid?`<div class="music-player-return"><button class="btn ghost sm tap" id="musicBack">${ic('chevL')} Your collection</button></div><section class="glass music-empty"><span aria-hidden="true">♪</span><h2>Bring a good song.</h2><p>Save a YouTube or YouTube Music link first, then play it inside HQ.</p><button class="btn tap" id="musicAdd">Save a discovery</button></section>`:embedded?`<div class="music-player-return"><button class="btn ghost sm tap" id="musicBack">${ic('chevL')} Your collection</button><a class="btn sm tap" href="${MIX}" target="_blank" rel="noopener" id="playerHandoff">YouTube Music ↗</a></div>`+legacyView():hubHTML();
V.music.after=()=>{document.getElementById('view').onclick=null;if(embedded&&!library().length&&!curVid){placeYT();document.getElementById('musicBack').onclick=()=>{embedded=false;render()};document.getElementById('musicAdd').onclick=()=>{embedded=false;render();addSheet()};return}if(embedded){legacyAfter();document.getElementById('musicBack').onclick=()=>{if(playing&&YTP)YTP.pauseVideo();embedded=false;render();placeYT()};document.getElementById('playerHandoff').onclick=()=>handoff()}else{placeYT();bindHub()}};
window.MUSIC_HUB={url,library};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!embedded&&document.body.dataset.view==='music')paint()});
// A home shortcut never initialises the embedded player or pretends to start personal shuffle.
document.addEventListener('click',e=>{if(e.target.closest('[data-music-handoff]'))handoff()});
})();
