/* HQ · three local games; animation only when something happens. */
(()=>{'use strict';
const symbols=['✦','☽','⌘','❖','◎','✳','♧','◈'];let game='memory',deck=[],open=[],matched=new Set(),moves=0,locked=false,wait=null,start=0,lights=[],lightMoves=0,react='idle',best={};
try{best=JSON.parse(localStorage.getItem('hq:play:best'))||{}}catch{}
function persist(){try{localStorage.setItem('hq:play:best',JSON.stringify(best))}catch{toast('Could not save your personal best.')}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cleanup(){clearTimeout(wait);wait=null;if(locked)open=[];locked=false;react='idle'}
function memoryNew(){cleanup();deck=shuffle([...symbols,...symbols]);open=[];matched=new Set();moves=0;start=performance.now()}
function toggleLight(a,i){for(const j of [i,i-4,i+4,...(i%4?[i-1]:[]),...(i%4<3?[i+1]:[])])if(j>=0&&j<16)a[j]=!a[j]}
function lightsNew(){cleanup();lights=Array(16).fill(false);for(let n=0;n<12;n++)toggleLight(lights,Math.floor(Math.random()*16));if(!lights.some(Boolean))toggleLight(lights,5);lightMoves=0}
function paint(){if(document.body.dataset.view!=='play')return;const el=$('#gameBoard'),status=$('#gameStatus');if(!el)return;const focused=document.activeElement,focusCard=focused?.dataset?.card,focusLight=focused?.dataset?.light,focusReaction=focused?.id==='reactionPad';
 if(game==='memory'){el.className='game-grid memory-grid';el.innerHTML=deck.map((v,i)=>`<button class="game-tile tap ${matched.has(i)?'matched':open.includes(i)?'flipped':''}" data-card="${i}" aria-label="${matched.has(i)?'Matched '+v:open.includes(i)?v:'Reveal card '+(i+1)}" ${matched.has(i)?'disabled':''}><span>${open.includes(i)||matched.has(i)?v:'·'}</span></button>`).join('');status.textContent=matched.size===16?'All pairs found · '+moves+' turns':moves+' turns · '+matched.size/2+' / 8 pairs';el.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>flip(+b.dataset.card))}
 else if(game==='lights'){el.className='game-grid lights-grid';el.innerHTML=lights.map((on,i)=>`<button class="game-tile light-tile tap ${on?'lit':''}" data-light="${i}" aria-pressed="${on}" aria-label="Light ${i+1}, ${on?'on':'off'}"><span>${on?'✦':'·'}</span></button>`).join('');const win=!lights.some(Boolean);status.textContent=win?'Perfect darkness · '+lightMoves+' moves':lightMoves+' moves · '+lights.filter(Boolean).length+' lights remain';el.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{if(win)return;toggleLight(lights,+b.dataset.light);lightMoves++;paint();if(!lights.some(Boolean)){if(!best.lights||lightMoves<best.lights){best.lights=lightMoves;persist()}celebrate()}})}
 else{el.className='reaction-wrap';el.innerHTML=`<button id="reactionPad" class="glass reaction-pad tap ${react}" aria-label="Reaction challenge"><span>${{idle:'Ready when you are.',waiting:'Wait for mint…',go:'NOW. ↗',early:'Too eager 🗿',done:'Nice catch.'}[react]}</span><small>${react==='idle'?'Tap to begin':react==='waiting'?'Stay still. Colour is the cue.':react==='go'?'Tap!': 'Tap to try again'}</small></button>`;$('#reactionPad').onclick=reactionTap}
 if(focusCard!==undefined){const b=el.querySelector(`[data-card="${focusCard}"]:not(:disabled)`)||el.querySelector('[data-card]:not(:disabled)');b?.focus({preventScroll:true})}if(focusLight!==undefined)el.querySelector(`[data-light="${focusLight}"]`)?.focus({preventScroll:true});if(focusReaction)$('#reactionPad')?.focus({preventScroll:true});
 $('#gameBest').textContent=game==='reaction'?(best.reaction?'Best '+best.reaction+' ms':'No personal best yet'):game==='memory'?(best.memory?'Best '+best.memory+' turns':'No personal best yet'):(best.lights?'Best '+best.lights+' moves':'No personal best yet')}
function celebrate(){const el=$('#gameBoard');if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&el?.animate)el.animate([{transform:'scale(1)'},{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:500,easing:'ease-out'});toast('Clean finish ✦')}
function flip(i){if(locked||matched.has(i)||open.includes(i))return;open.push(i);paint();if(open.length!==2)return;moves++;if(deck[open[0]]===deck[open[1]]){open.forEach(i=>matched.add(i));open=[];paint();if(matched.size===16){if(!best.memory||moves<best.memory){best.memory=moves;persist()}paint();celebrate()}}else{locked=true;wait=setTimeout(()=>{open=[];locked=false;paint()},800)}}
function reactionTap(){if(react==='waiting'){clearTimeout(wait);react='early';$('#gameStatus').textContent='Early tap. Try again.';paint();return}if(react==='go'){const ms=Math.round(performance.now()-start);react='done';if(!best.reaction||ms<best.reaction){best.reaction=ms;persist()}paint();$('#gameStatus').textContent=ms+' ms · browser timing, just for fun';return}react='waiting';paint();$('#gameStatus').textContent='Wait for the colour change.';wait=setTimeout(()=>{if(document.hidden||document.body.dataset.view!=='play'){cleanup();return}requestAnimationFrame(()=>{if(document.body.dataset.view==='play'&&!document.hidden&&react==='waiting'){react='go';start=performance.now();paint()}})},1200+Math.random()*2600)}
V.play=()=>`<section class="phead"><div class="kicker">09 / A LITTLE DOWNTIME</div><div class="ptitle">play a little<i>.</i></div></section><p class="muted">No account, no ads, no connection. Just one more round.</p><section class="glass play-workspace"><div class="seg play-tabs">${[['memory','Pairs'],['lights','Lights Out'],['reaction','Quick Draw']].map(([id,n])=>`<button data-game="${id}" class="${game===id?'on':''}">${n}</button>`).join('')}</div><div class="play-intro"><h2>${{memory:'Find your other half.',lights:'Turn the constellation off.',reaction:'How fast is that thumb?'}[game]}</h2><p>${{memory:'Reveal two cards. Find all eight pairs in as few turns as you can.',lights:'Each tap flips that light and its neighbours. Every board starts from a solvable position.',reaction:'Wait for mint and “NOW”, then tap. Jump the cue and you restart.'}[game]}</p></div><div class="row between game-info"><span id="gameStatus" role="status"></span><span id="gameBest" class="small muted"></span></div><div id="gameBoard"></div><div class="row between play-footer"><button class="btn tap" id="gameReset">New round ↻</button><span class="small muted">Personal bests stay on this device.</span></div></section>`;
V.play.after=()=>{if(game==='memory'&&!deck.length)memoryNew();if(game==='lights'&&!lights.length)lightsNew();document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{cleanup();game=b.dataset.game;render()});$('#gameReset').onclick=()=>{if(game==='memory')memoryNew();else if(game==='lights')lightsNew();else cleanup();paint();if(game==='reaction')$('#gameStatus').textContent='Tap to begin.'};paint()};
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(wait);if(game==='reaction'){react='idle';paint()}else if(locked){open=[];locked=false;paint()}}});
window.PlayCorner={leave:cleanup,toggleLight,newLights:lightsNew};
})();
